[package]
name = "metro-common"
version = "0.1.0"
edition = "2024"

[features]
# Build with the standard library by default
default = ["no_std"]
std = ["serde/std"]

# no_std build
no_std = ["dep:heapless"]

[dependencies]
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
heapless = { version = "0.9.1", optional = true, features = ["serde"] }
